- name: Debugging with tmate
  # You may pin to the exact commit or the version.
  # uses: mxschmitt/action-tmate@1005f9c9db5f1b055a495e72c6e589764984baf6
  uses: mxschmitt/action-tmate@v3.14
  with:
    # If apt should be executed with sudo or without
    sudo: # optional, default is auto
    # Whether or not to install dependencies for tmate on linux (openssh-client, xz-utils)
    install-dependencies: # optional, default is true
    # If only the public SSH keys of the user triggering the workflow should be authorized
    limit-access-to-actor: # optional, default is false
    # The hostname for your tmate server (e.g. ssh.example.org)
    tmate-server-host: # optional, default is 
    # The port for your tmate server (e.g. 2222)
    tmate-server-port: # optional, default is 
    # The RSA fingerprint for your tmate server
    tmate-server-rsa-fingerprint: # optional, default is 
    # The ed25519 fingerprint for your tmate server
    tmate-server-ed25519-fingerprint: # optional, default is 
    # Personal access token (PAT) used to call into GitHub's REST API. We recommend using a service account with the least permissions necessary. Also when generating a new PAT, select the least scopes necessary. [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)

    github-token: # optional, default is ${{ github.token }}
