name: libfreenect2
on:
  push:
    paths:
      - libfreenect2/**
      - .github/workflows/libfreenect2.yml
  workflow_dispatch:
env:
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  linux-x86_64:
    runs-on: ubuntu-22.04
    container: centos:7
    steps:
      - name: Enable CUDA for deployment
        run: echo "CI_DEPLOY_NEED_CUDA=1" >> $GITHUB_ENV
      - name: Build for '${{ env.CI_DEPLOY_PLATFORM }}'
        uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
      - name: Show file structure on failure
        if: failure()
        run: |
          cat `find / -name '*.cmake.rej' -print` || true
          ls /usr/local | grep -i cuda || true
      - name: Start SSH session on failure
        if: failure()
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
