name: libfreenect2
on:
  push:
    paths:
      - libfreenect2/**
      - .github/workflows/libfreenect2.yml
  pull_request:
    paths:
      - libfreenect2/**
      - .github/workflows/libfreenect2.yml
  workflow_dispatch:
env:
  CI_DEPLOY_NEED_CUDA: 1
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  linux-x86:
    runs-on: ubuntu-20.04
    container: centos:7
    steps:
      - name: Build for 'linux-x86'
        uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
        continue-on-error: true
      - name: Show file structure
        run: |
          yum -y install tree
          tree -aS 
          tree -aS /usr/local
      - name: Start SSH session
        uses: mxschmitt/action-tmate@v3
        continue-on-error: true
        timeout-minutes: 10
  linux-x86_64:
    runs-on: ubuntu-20.04
    container: centos:7
    steps:
      - name: Build for 'linux-x86_64'
        uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
        continue-on-error: true
      - name: Show file structure
        run: |
          yum -y install tree
          tree -aS 
          tree -aS /usr/local
      - name: Start SSH session
        uses: mxschmitt/action-tmate@v3
        continue-on-error: true
        timeout-minutes: 10
  macosx-x86_64:
    runs-on: macos-11
    steps:
      - name: Build for 'macosx-x86_64'
        uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
        continue-on-error: true
      - name: Show file structure
        run: |
          brew install tree
          tree -aS
          tree -aS /usr/local
      - name: Start SSH session
        uses: mxschmitt/action-tmate@v3
        continue-on-error: true
        timeout-minutes: 10
  windows-x86_64:
    runs-on: windows-2019
    steps:
      - name: Build for 'windows-x86_64'
        uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
        continue-on-error: true
      - name: Show file structure
        run: |
          tree /f /a C:\
      - name: Start SSH session
        uses: mxschmitt/action-tmate@v3
        continue-on-error: true
        timeout-minutes: 10
  redeploy:
    needs: [linux-x86, linux-x86_64, macosx-x86_64, windows-x86_64]
    runs-on: ubuntu-20.04
    steps:
      - name: Redeploy
        uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
      - name: Start SSH session
        uses: mxschmitt/action-tmate@v3
        continue-on-error: true
        timeout-minutes: 10
