name: libfreenect2
on:
  push:
    paths:
      - libfreenect2/**
      - .github/workflows/libfreenect2.yml
  pull_request:
    paths:
      - libfreenect2/**
      - .github/workflows/libfreenect2.yml
  workflow_dispatch:
env:
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  linux-x86:
    runs-on: ubuntu-20.04
    container: centos:7
    steps:
      - name: Build for '${{ github.job }}'
        uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
        #continue-on-error: true
      - name: Show file structure
        run: |
          yum -y install tree
          tree -a
          echo "x-={[X]}=-x"
          tree -a /usr/local
  linux-x86_64:
    runs-on: ubuntu-20.04
    container: centos:7
    steps:
      - name: Enable CUDA for deployment
        run: |
          echo "CI_DEPLOY_NEED_CUDA=1" >> $GITHUB_ENV
      - name: Build for '${{ github.job }}'
        uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
        #continue-on-error: true
      - name: Show file structure
        run: |
          yum -y install tree
          tree -a
          echo "x-={[X]}=-x"
          tree -a /usr/local
  macosx-x86_64:
    runs-on: macos-11
    steps:
      - name: Build for '${{ github.job }}'
        uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
        #continue-on-error: true
      - name: Show file structure
        run: |
          brew install tree
          tree -a
          echo "x-={[X]}=-x"
          tree -a /usr/local
      #- name: Start SSH session
      #  uses: mxschmitt/action-tmate@v3
      #  continue-on-error: true
      #  timeout-minutes: 10
  windows-x86_64:
    runs-on: windows-2019
    steps:
      - name: Enable CUDA for deployment
        run: |
          echo "CI_DEPLOY_NEED_CUDA=1" >> $env:GITHUB_ENV
      - name: Build for '${{ github.job }}'
        uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
        continue-on-error: true
      - name: Show CMake output
        #D:\a\javacpp-presets\javacpp-presets\CMakeFiles\CMakeOutput.log
        #D:/a/javacpp-presets/javacpp-presets/libfreenect2/cppbuild/windows-x86_64/libfreenect2-0.2.0/CMakeFiles/CMakeOutput.log
        #type ./${{ github.workflow }}/cppbuild/${{ github.job }}/libfreenect2-$LIBFREENECT2_VERSION/CMakeFiles/CMakeOutput.log
        run: |
          type "$INSTALL_PATH/CMakeFiles/CMakeOutput.log"
      - name: Show file structure
        run: |
          tree /f /a
          echo "x-={[X]}=-x"
          tree /f /a "$CUDA_PATH/../.."
      - name: Start SSH session
        uses: mxschmitt/action-tmate@v3
        continue-on-error: true
        timeout-minutes: 10
  redeploy:
    needs: [linux-x86, linux-x86_64, macosx-x86_64, windows-x86_64]
    runs-on: ubuntu-20.04
    steps:
      - name: Redeploy
        uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
      - name: Start SSH session
        uses: mxschmitt/action-tmate@v3
        continue-on-error: true
        timeout-minutes: 5
