name: systems
on:
  push:
    paths:
      - systems/**
      - .github/workflows/systems.yml
  pull_request:
    paths:
      - systems/**
      - .github/workflows/systems.yml
  workflow_dispatch:
env:
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  linux-armhf:
    runs-on: ubuntu-20.04
    container: ubuntu:bionic
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
      - name: Setup linux-armhf
        uses: mxschmitt/action-tmate@v3
  linux-arm64:
    runs-on: ubuntu-20.04
    container: ubuntu:bionic
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
      - name: Setup linux-arm64
        uses: mxschmitt/action-tmate@v3
  linux-ppc64le:
    runs-on: ubuntu-20.04
    container: ubuntu:bionic
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
      - name: Setup linux-ppc64le
        uses: mxschmitt/action-tmate@v3
  linux-x86:
    runs-on: ubuntu-20.04
    container: centos:7
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
      - name: Setup linux-x86
        uses: mxschmitt/action-tmate@v3
  linux-x86_64:
    runs-on: ubuntu-20.04
    container: centos:7
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
      - name: Setup linux-x86_64
        uses: mxschmitt/action-tmate@v3
  macosx-x86_64:
    runs-on: macos-11
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
      - name: Setup macosx-x86_64
        uses: mxschmitt/action-tmate@v3
  windows-x86:
    runs-on: windows-2019
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
      - name: Setup windows-x86
        uses: mxschmitt/action-tmate@v3
  windows-x86_64:
    runs-on: windows-2019
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
      - name: Setup windows-x86_64
        uses: mxschmitt/action-tmate@v3
  redeploy:
    needs: [linux-armhf, linux-arm64, linux-ppc64le, linux-x86, linux-x86_64, macosx-x86_64, windows-x86, windows-x86_64]
    runs-on: ubuntu-20.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
      - name: Redeploy
        uses: mxschmitt/action-tmate@v3